name: CI

on:
  push:
    branches-ignore:
      - "main"
    paths-ignore:
      - "**.md"
      - ".vscode/"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".vscode/"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
